### ISSUE TITLE
about the sar images

### ISSUE THREAD

**Issue by cannonli7** [motokimura/spacenet6_solution#35]
Thanks for your work. I downloaded the spacenet-6 dataset but found that all the sar images are binary images, could you please help me with that problem

**Comment by motokimura** [comment]
Thanks for your interest.
What do you want to do with SpaceNet-6 images?

If you just want to visualize the image, this function may help. https://github.com/motokimura/spacenet6_solution/blob/e0b9782e559286d09073c8bbff588f83aa3f412e/notebooks/utils.py#L5

You can find the visualization examples here.
https://github.com/motokimura/spacenet6_solution/blob/master/notebooks/test_spacenet6.ipynb

**Comment by cannonli7** [comment]
Thanks a lot



At 2021-04-26 19:10:08, "Motoki Kimura" ***@***.***> wrote:

Thanks for your interest.
What do you want to do with SpaceNet-6 images?

If you just want to visualize the image, this function may help. https://github.com/motokimura/spacenet6_solution/blob/e0b9782e559286d09073c8bbff588f83aa3f412e/notebooks/utils.py#L5

You can find the visualization examples here.
https://github.com/motokimura/spacenet6_solution/blob/master/notebooks/test_spacenet6.ipynb

**Comment by cannonli7** [comment]
> Thanks for your interest.
> What do you want to do with SpaceNet-6 images?
> 
> If you just want to visualize the image, this function may help.
> 
> https://github.com/motokimura/spacenet6_solution/blob/e0b9782e559286d09073c8bbff588f83aa3f412e/notebooks/utils.py#L5
> 
> You can find the visualization examples here.
> https://github.com/motokimura/spacenet6_solution/blob/master/notebooks/test_spacenet6.ipynb

sorry to bother you again, I think I made some mistake while downloading the dataset because I open the images in folder "SAR-Intensity" in photoshop and found the images are really binary images could you please share a link to download the SAR images

**Comment by motokimura** [comment]
Please see readme.
https://github.com/motokimura/spacenet6_solution#download-spacenet6-data

**Comment by cannonli7** [comment]
It seems that photoshop can load load the image with decimal pixel values in a right way, I load the image with skimage and solve the problem, really sorry to bother you



在 2021-04-26 20:16:52，"Motoki Kimura" ***@***.***> 写道：

Please see readme.
https://github.com/motokimura/spacenet6_solution#download-spacenet6-data

**Comment by motokimura** [comment]
Glad to hear the problem has been solved!
